Ti.include("TabGroup1.js"); //generated by ForgeUI
Ti.include("draw-win_map.js");

Ti.Geolocation.purpose = "To show your location on the map";
Ti.UI.backgroundColor = 'white';

var m_TabGroup1 = new FUI.TabGroup_1(); //generated by ForgeUI

m_TabGroup1.createAttachChTabGroup_1(); //generated by ForgeUI


var win2 = Ti.UI.createWindow();
var image = Ti.UI.createImageView({
  image:'http://www.petside.com/sites/default/files/imagecache/thumbnail_50x50/Dog1.JPG'
});
win2.add(image);


m_TabGroup1.tab_3.window = win_map;
m_TabGroup1.tab_2.window = win2;

m_TabGroup1.tab_1.icon = "images/profile.png"; //Profile
m_TabGroup1.tab_2.icon = "images/createobjective.png"; //Create Objective
m_TabGroup1.tab_3.icon = "images/mylocation.png"; //My Location / Map View
m_TabGroup1.tab_4.icon = "images/friends.png"; //Friends
m_TabGroup1.tab_5.icon = "images/settings.png"; //Settings


m_TabGroup1.tabGroup_1.open();
m_TabGroup1.tab_3.setActive();


//Create Objective
//Launch Mission